title: Project Portfolio
description: Welcome to my data science portfolio! Here, you will find a collection of my projects showcasing my expertise in data analysis, machine learning and data visualization. 
theme: jekyll-theme-cayman
